# TCH data

```{r}
library(metrumrg)
library(tidyverse)
library(forcats)
library(mrgsolve)
library(satchel)
library(PKPDmisc)

```

```{r}
demog <- read_csv("../data/derived/tch_vanco.csv") %>% 
  distinct(PTID, .keep_all=TRUE) %>% rename(AGEyr=AGE) %>% 
  mutate(GFR =  round((0.41*HT)/SCR,2),
         AGE = AGEyr*365) %>% 
  rename(ID = PTID, BW=WT, ISM = M) %>% 
  select(ID,AGE,AGEyr,BW,ISM,SCR,GFR)
```

```{r}
satchel <- Satchel$new("tch_vanc", "../data/derived/satchel")
```


```{r}
models <- source("../modeling/models.R")$value

models$available()
```

```{r}
mod <- models$use("capparelli")
ind <- models$use("cap_ind")
#mod <- models$use("stockmann")
```

```{r}
demog %>% ggplot+geom_histogram(aes(x=SCR), bins=80)
demog %>% ggplot+geom_point(aes(x=AGE,y=SCR))
```


```{r}
possible_regimens <- expand.grid(
  amtperkg = seq(5, 25, 5), 
  ii = c(6, 8, 12)) %>% 
  arrange(amtperkg) %>% mutate(reg=1:nrow(.))
```

```{r}
cli_vi <- mod %>% data_set(
  demog %>% mutate(time = 0, cmt = 1, evid=1)
) %>% carry.out(GFR,AGEyr) %>% mrgsim(end = 0) %>% 
  mutate(cmt = 1, evid=1) %>% distinct(ID,.keep_all=TRUE)

ex_id <- cli_vi %>% slice(1)

full_id <- full_join(ex_id, possible_regimens %>% mutate(ID = ex_id$ID)) %>%
  mutate(amt = amtperkg*BW,
         rate = amt,
         evid = 1,
         addl=7,
         OID = ID,
         ID = 1:nrow(.),
         CL = CL,
         V = Vc)


ind_results <- ind %>%
  data_set(full_id) %>%  carry.out(evid,reg) %>% 
     mrgsim(end=90,delta=0.1,digits=4) %>%
  as.data.frame %>%
  full_join(full_id %>% select(ID, amt, ii,GFR,AGEyr))

full_ind_results <- ind_results %>% 
  filter(evid!=1) %>%
  mutate(cmin =  ifelse(time%%ii==0,DV,NA)) %>%
  fill(cmin) %>% 
  mutate(cmint = ifelse(time%%ii==0,paste0("c",time),NA)) %>% 
  fill(cmint) %>%
  mutate(DAY = floor(time/24)) %>% 
  group_by(ID, amt, ii) %>% 
  mutate(AUC24 = round(PKPDmisc:::auc_partial_cpp(time, DV, c(0, 24)),2)) %>%
  mutate(AUC48 = round(PKPDmisc:::auc_partial_cpp(time, DV, c(24, 48)),2)) %>%
  mutate(AGE = round(AGE/365.24,2)) %>% 
  distinct(ID,cmint, .keep_all=TRUE)
  

```

```{r}
#All individuals
ind_auc_vs_trough <- function(ex_id, possible_regimens,ind_model) {
  possible_regimens$ID <- ex_id$ID 
  full_id <- suppressMessages(
    full_join(ex_id, possible_regimens) %>%
    mutate(amt = amtperkg*BW,
         rate = amt,
         evid = 1,
         addl=7,
         OID = ID,
         ID = 1:nrow(.),
         CL = CL,
         V = Vc)
  )

  ind_results <- suppressMessages(
    ind %>%
  data_set(full_id) %>%  carry.out(OID,evid,reg) %>% 
     mrgsim(end=90,delta=0.1,digits=4) %>%
  as.data.frame %>%
  full_join(full_id %>% select(ID, amt, ii,GFR,AGEyr))
  )
  
  full_ind_results <- ind_results %>% 
  filter(evid!=1) %>%
  mutate(cmin =  ifelse(time%%ii==0,DV,NA)) %>%
  fill(cmin) %>% 
  mutate(cmint = ifelse(time%%ii==0,paste0("c",time),NA)) %>% 
  fill(cmint) %>%
  mutate(DAY = floor(time/24)) %>% 
  group_by(ID, amt, ii) %>% 
  mutate(AUC24 = round(PKPDmisc:::auc_partial_cpp(time, DV, c(0, 24)),2)) %>%
  mutate(AUC48 = round(PKPDmisc:::auc_partial_cpp(time, DV, c(24, 48)),2)) %>%
  mutate(AGE = round(AGE/365.24,2)) %>% 
  distinct(ID,cmint, .keep_all=TRUE)

  return(full_ind_results)
}
```

```{r}
all_inds <- cli_vi %>% 
  by_row(function(row) {
    ind_auc_vs_trough(row, possible_regimens, ind)
  }, .collate="rows")
```

```{r}
all_inds$NID <- all_inds$.row
all_inds <- all_inds[,14:36]
```

```{r}
all_sims <- all_inds %>%
  mutate(RF =  ifelse(GFR>90,">90",
               ifelse(between(GFR,60,90),"60-90",
               ifelse(between(GFR,30,60),"30-60",
               ifelse(between(GFR,15,30),"15-30",
               ifelse(GFR<15,"<15", NA)))))) %>% 
  mutate(RF = fct_relevel(RF,">90","60-90","30-60","15-30","<15"))
#satchel$save(all_sims)
```



```{r}
p1 <- demog %>% 
  ggplot(aes(x=AGEyr,y=SCR))+
  geom_point()+
  scale_y_continuous(breaks = c(0,0.4,0.8,1.2,2,3,4,8,10))+
  theme_bw()+
  PKPDmisc::base_theme(axis_text_x = 20,axis_title_x = 22)+
  geom_hline(yintercept = 0.7,color="red")+
  labs(
    x = "Age (years)",y="Serum Creatinine (mg/dL)",
    title = "Distribution of Serum Creatinine over Age",
    subtitle = "",
    caption = "1449 patients sampled from large pediatric database from TCH"
  )
p1
```


```{r}
p2 <- demog %>% 
  ggplot(aes(x=AGEyr,y=BW))+
  geom_point()+
  theme_bw()+
  PKPDmisc::base_theme(axis_text_x = 20,axis_title_x = 22)+
  labs(
    x = "Age (years)",y="Body Weight (kg)",
    title = "Distribution of Body Weight over Age",
    subtitle = "",
    caption = "1449 patients sampled from large pediatric database from TCH"
  )
p2
  
```

```{r}
all_sims %>% distinct(NID,.keep_all=TRUE) %>% 
  mutate(agemin = min(AGEyr),
         agemax = max(AGEyr),
         AGE_Range = paste0(agemin,"-",agemax)) %>% 
  ungroup %>% group_by(RF) %>% 
  count(AGE_Range)
```

```{r}
p3 <- all_sims %>% 
  filter(ii==6) %>% 
  filter(cmint%in%c("c6","c12","c18","c24","c30","c36","c42")) %>% 
  mutate(cmint = fct_reorder(cmint,time)) %>% 
  mutate(dose = round(amt/BW)) %>% 
  filter(dose!=5) %>% 
  ggplot(aes(x=cmin,fill=RF))+
  geom_histogram(bins=30,alpha=0.7)+
  facet_grid(cmint~dose, labeller = label_both)+
  geom_vline(xintercept = c(10,20), color="red")+
  theme_bw()+
  theme(legend.position = "top",
        plot.title = element_text(size=12,face="bold"),
        plot.caption = element_text(face="italic"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(size=18,angle = 90),
        axis.text.y = element_text(size=18),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        axis.title  = element_text(size = 16),
        strip.text = element_text(size=16))+
  labs(
    x = "Vancomycin Trough Concentration (mg/L)",y="Number of subjects",
    title = "Distribution of Ctrough's for q6 dosing interval",
    subtitle = "Dose (mg/kg) and cmint is trough before the c-hour",
    caption = "PK simulated from Le et al., 2013"
  )
p3
```


```{r}
p4 <- all_sims %>% 
  filter(ii==8) %>% 
  filter(cmint%in%c("c8","c16","c24","c32","c40")) %>% 
  mutate(cmint = fct_reorder(cmint,time)) %>% 
  mutate(dose = round(amt/BW)) %>% 
  filter(dose!=5) %>% 
  ggplot(aes(x=cmin,fill=RF))+
  geom_histogram(bins=30,alpha=0.7)+
  facet_grid(cmint~dose, labeller = label_both)+
  geom_vline(xintercept = c(10,20), color="red")+
  theme_bw()+
  theme(legend.position = "top",
        plot.title = element_text(size=12,face="bold"),
        plot.caption = element_text(face="italic"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(size=18,angle = 90),
        axis.text.y = element_text(size=18),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        axis.title  = element_text(size = 16),
        strip.text = element_text(size=16))+
  labs(
    x = "Vancomycin Trough Concentration (mg/L)",y="Number of subjects",
    title = "Distribution of Ctrough's for q8 dosing interval",
    subtitle = "Dose (mg/kg) and cmint is trough before the c-hour",
    caption = "PK simulated from Le et al., 2013"
  )
p4
```


```{r}
p5 <- all_sims %>% 
  filter(ii==12) %>% 
  filter(cmint%in%c("c12","c24","c48")) %>% 
  mutate(cmint = fct_reorder(cmint,time)) %>% 
  mutate(dose = round(amt/BW)) %>% 
  filter(dose!=5) %>% 
  ggplot(aes(x=cmin,fill=RF))+
  geom_histogram(bins=30,alpha=0.7)+
  facet_grid(cmint~dose, labeller = label_both)+
  geom_vline(xintercept = c(10,20), color="red")+
  theme_bw()+
  theme(legend.position = "top",
        plot.title = element_text(size=12,face="bold"),
        plot.caption = element_text(face="italic"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(size=18,angle = 90),
        axis.text.y = element_text(size=18),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        axis.title  = element_text(size = 16),
        strip.text = element_text(size=16))+
  labs(
    x = "Vancomycin Trough Concentration (mg/L)",y="Number of subjects",
    title = "Distribution of Ctrough's for q12 dosing interval",
    subtitle = "Dose (mg/kg) and cmint is trough before the c-hour",
    caption = "PK simulated from Le et al., 2013"
  )
p5
```

```{r}
p6 <- all_sims %>% 
  mutate(dose = round(amt/BW)) %>% 
  filter(dose!=5) %>% 
  distinct(NID,reg,.keep_all=TRUE) %>%
  ggplot(aes(x=AUC24,fill=RF))+
  geom_histogram(bins=30,alpha=0.7)+
  facet_grid(ii~dose, labeller = label_both)+
  geom_vline(xintercept = 400, color="red")+
  theme_bw()+
  theme(legend.position = "top",
        plot.title = element_text(size=12,face="bold"),
        plot.caption = element_text(face="italic"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(size=18,angle = 90),
        axis.text.y = element_text(size=18),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        axis.title  = element_text(size = 16),
        strip.text = element_text(size=16))+
  scale_x_continuous(breaks = c(0,200,400,600,1000,1500))+
  labs(
    x = "AUC0-24 hrs",y="Number of subjects",
    title = "Distribution of AUC0-24hr",
    subtitle = "Dose (mg/kg) and ii is dosing interval (tau - hrs)",
    caption = "PK simulated from Le et al., 2013"
  )
p6
```

```{r}
p7 <- all_sims %>% 
  mutate(dose = round(amt/BW)) %>% 
  filter(dose!=5) %>% 
  distinct(NID,reg,.keep_all=TRUE) %>%
  ggplot(aes(x=AUC48,fill=RF))+
  geom_histogram(bins=30,alpha=0.7)+
  facet_grid(ii~dose, labeller = label_both)+
  geom_vline(xintercept = 400, color="red")+
  theme_bw()+
  theme(legend.position = "top",
        plot.title = element_text(size=12,face="bold"),
        plot.caption = element_text(face="italic"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(size=18,angle = 90),
        axis.text.y = element_text(size=18),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        axis.title  = element_text(size = 16),
        strip.text = element_text(size=16))+
  scale_x_continuous(breaks = c(0,200,400,600,1000,1500))+
  labs(
    x = "AUC24-48 hrs",y="Number of subjects",
    title = "Distribution of AUC24-48hr",
    subtitle = "Dose (mg/kg) and ii is dosing interval (tau - hrs)",
    caption = "PK simulated from Le et al., 2013"
  )
p7
```


```{r}
p8 <- all_sims %>% 
  mutate(dose = round(amt/BW)) %>% 
  filter(dose!=5) %>% 
  mutate(thalf = round((0.693*V)/CL,2)) %>% 
  distinct(NID,reg,.keep_all=TRUE) %>%
  mutate(HL =  PKPDmisc::set_bins(thalf)) %>% 
  group_by(HL) %>% 
  mutate(hlmin = min(thalf),
         hlmax = max(thalf),
         HL_Range = paste0(hlmin,"-",hlmax)) %>% 
  ggplot(aes(x=AUC24,fill=HL_Range))+
  geom_histogram(bins=30,alpha=0.7)+
  facet_grid(ii~dose, labeller = label_both)+
  geom_vline(xintercept = 400, color="red")+
  theme_bw()+
  theme(legend.position = "top",
        plot.title = element_text(size=12,face="bold"),
        plot.caption = element_text(face="italic"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(size=18,angle = 90),
        axis.text.y = element_text(size=18),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        axis.title  = element_text(size = 16),
        strip.text = element_text(size=16))+
  scale_x_continuous(breaks = c(0,200,400,600,1000,1500))+
  labs(
    x = "AUC0-24 hrs",y="Number of subjects",
    title = "Distribution of AUC0-24hr by half-life",
    subtitle = "Dose (mg/kg) and ii is dosing interval (tau - hrs)",
    caption = "PK simulated from Le et al., 2013"
  )
p8
```

```{r}
p9 <- all_sims %>% 
  mutate(dose = round(amt/BW)) %>% 
  filter(dose!=5,time!=0,time<=24,ii==6) %>% 
  mutate(cmint = fct_reorder(cmint,time)) %>% 
  ggplot(aes(x=AUC24,y=cmin,color=cmint))+
  geom_point()+
  geom_hline(yintercept = c(10,20),color="grey",size=0.8)+
  geom_vline(xintercept = 400,color="grey", size=0.8)+
  facet_grid(RF~dose,labeller = label_both)+
  theme_bw()+
  theme(legend.position = "top",
        plot.title = element_text(size=12,face="bold"),
        plot.caption = element_text(face="italic"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(size=18,angle = 90),
        axis.text.y = element_text(size=18),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        axis.title  = element_text(size = 16),
        strip.text = element_text(size=16))+
  scale_x_continuous(breaks = c(0,200,400,600,1000,1500))+
  scale_color_discrete(name="Time of Trough (h)")+
  labs(
    x = "AUC0-24 hrs",y="Vancomycin Ctrough (mg/L)",
    title = "Correlation of Ctrough with AUC0-24 for q6 dosing",
    subtitle = "Dose (mg/kg)",
    caption = "PK simulated from Le et al., 2013"
  )
p9  
```

```{r}
p10 <- all_sims %>% 
  mutate(dose = round(amt/BW)) %>% 
  filter(dose!=5,time>24,time<=48,ii==6) %>% 
  mutate(cmint = fct_reorder(cmint,time)) %>% 
  ggplot(aes(x=AUC48,y=cmin,color=cmint))+
  geom_point()+
  geom_hline(yintercept = c(10,20),color="grey",size=0.8)+
  geom_vline(xintercept = 400,color="grey", size=0.8)+
  facet_grid(RF~dose,labeller = label_both)+
  theme_bw()+
  theme(legend.position = "top",
        plot.title = element_text(size=12,face="bold"),
        plot.caption = element_text(face="italic"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(size=18,angle = 90),
        axis.text.y = element_text(size=18),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        axis.title  = element_text(size = 16),
        strip.text = element_text(size=16))+
  scale_x_continuous(breaks = c(0,200,400,600,1000,1500))+
  scale_color_discrete(name="Time of Trough (h)")+
  labs(
    x = "AUC24-48 hrs",y="Vancomycin Ctrough (mg/L)",
    title = "Correlation of Ctrough with AUC24-48 for q6 dosing",
    subtitle = "Dose (mg/kg)",
    caption = "PK simulated from Le et al., 2013"
  )
p10  
```


```{r}
p11 <- all_sims %>% 
  mutate(dose = round(amt/BW)) %>% 
  filter(dose!=5,time!=0,time<=24,ii==8) %>% 
  mutate(cmint = fct_reorder(cmint,time)) %>% 
  ggplot(aes(x=AUC24,y=cmin,color=cmint))+
  geom_point()+
  geom_hline(yintercept = c(10,20),color="grey",size=0.8)+
  geom_vline(xintercept = 400,color="grey", size=0.8)+
  facet_grid(RF~dose,labeller = label_both)+
  theme_bw()+
  theme(legend.position = "top",
        plot.title = element_text(size=12,face="bold"),
        plot.caption = element_text(face="italic"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(size=18,angle = 90),
        axis.text.y = element_text(size=18),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        axis.title  = element_text(size = 16),
        strip.text = element_text(size=16))+
  scale_x_continuous(breaks = c(0,200,400,600,1000,1500))+
  scale_color_discrete(name="Time of Trough (h)")+
  labs(
    x = "AUC0-24 hrs",y="Vancomycin Ctrough (mg/L)",
    title = "Correlation of Ctrough with AUC0-24 for q8 dosing",
    subtitle = "Dose (mg/kg)",
    caption = "PK simulated from Le et al., 2013"
  )
p11  
```

```{r}
p12 <- all_sims %>% 
  mutate(dose = round(amt/BW)) %>% 
  filter(dose!=5,time>24,time<=48,ii==8) %>% 
  mutate(cmint = fct_reorder(cmint,time)) %>% 
  ggplot(aes(x=AUC48,y=cmin,color=cmint))+
  geom_point()+
  geom_hline(yintercept = c(10,20),color="grey",size=0.8)+
  geom_vline(xintercept = 400,color="grey", size=0.8)+
  facet_grid(RF~dose,labeller = label_both)+
  theme_bw()+
  theme(legend.position = "top",
        plot.title = element_text(size=12,face="bold"),
        plot.caption = element_text(face="italic"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(size=18,angle = 90),
        axis.text.y = element_text(size=18),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        axis.title  = element_text(size = 16),
        strip.text = element_text(size=16))+
  scale_x_continuous(breaks = c(0,200,400,600,1000,1500))+
  scale_color_discrete(name="Time of Trough (h)")+
  labs(
    x = "AUC24-48 hrs",y="Vancomycin Ctrough (mg/L)",
    title = "Correlation of Ctrough with AUC24-48 for q8 dosing",
    subtitle = "Dose (mg/kg)",
    caption = "PK simulated from Le et al., 2013"
  )
p12  
```


```{r}
p13 <- all_sims %>% 
  mutate(dose = round(amt/BW)) %>% 
  filter(dose!=5,time!=0,time<=24,ii==12) %>% 
  mutate(cmint = fct_reorder(cmint,time)) %>% 
  ggplot(aes(x=AUC24,y=cmin,color=cmint))+
  geom_point()+
  geom_hline(yintercept = c(10,20),color="grey",size=0.8)+
  geom_vline(xintercept = 400,color="grey", size=0.8)+
  facet_grid(RF~dose,labeller = label_both)+
  theme_bw()+
  theme(legend.position = "top",
        plot.title = element_text(size=12,face="bold"),
        plot.caption = element_text(face="italic"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(size=18,angle = 90),
        axis.text.y = element_text(size=18),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        axis.title  = element_text(size = 16),
        strip.text = element_text(size=16))+
  scale_x_continuous(breaks = c(0,200,400,600,1000,1500))+
  scale_color_discrete(name="Time of Trough (h)")+
  labs(
    x = "AUC0-24 hrs",y="Vancomycin Ctrough (mg/L)",
    title = "Correlation of Ctrough with AUC0-24 for q12 dosing",
    subtitle = "Dose (mg/kg)",
    caption = "PK simulated from Le et al., 2013"
  )
p13  
```

```{r}
p14 <- all_sims %>% 
  mutate(dose = round(amt/BW)) %>% 
  filter(dose!=5,time>24,time<=48,ii==12) %>% 
  mutate(cmint = fct_reorder(cmint,time)) %>% 
  ggplot(aes(x=AUC48,y=cmin,color=cmint))+
  geom_point()+
  geom_hline(yintercept = c(10,20),color="grey",size=0.8)+
  geom_vline(xintercept = 400,color="grey", size=0.8)+
  facet_grid(RF~dose,labeller = label_both)+
  theme_bw()+
  theme(legend.position = "top",
        plot.title = element_text(size=12,face="bold"),
        plot.caption = element_text(face="italic"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(size=18,angle = 90),
        axis.text.y = element_text(size=18),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        axis.title  = element_text(size = 16),
        strip.text = element_text(size=16))+
  scale_x_continuous(breaks = c(0,200,400,600,1000,1500))+
  scale_color_discrete(name="Time of Trough (h)")+
  labs(
    x = "AUC24-48 hrs",y="Vancomycin Ctrough (mg/L)",
    title = "Correlation of Ctrough with AUC24-48 for q12 dosing",
    subtitle = "Dose (mg/kg)",
    caption = "PK simulated from Le et al., 2013"
  )
p14
  
```



```{r eval=FALSE}
cairo_pdf("../reports/tch_le_preds.pdf", onefile = TRUE, width = 14, height=10)
p1
p2
p3
p4
p5
p6
p7
p8
p9
p10
p11
p12
p13
p14
# p15
# p16
# p17
# p18
# p19
# p20
# p21
# p22
# p23
# p24
# p25
# p26
# p27
# p28
# p29
# p30
# p31
# p32
# p33
# p34
# p35
# p36
# p37
# p38
# p39
dev.off()
```

